# -*- coding: utf-8 -*-
"""class6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1En-t2NdJzFK5PDdD7gVRZjAIEfTq-qvp
"""

def funcao_principal():
# Bloco de código da função principal
  variavel1 = 10
  variavel2 = 20

  if variavel1 < variavel2:
# Bloco de código do if
    print("Variável 1 é menor que Variável 2")
  else:
# Bloco de código do else
    print("Variável 1 é maior ou igual a Variável 2")
funcao_principal()

for i in range(5):
  # Bloco de código do loop for
  print(f"Valor de i: {i}")

    # Fim do bloco de código da função principal

# Fim do bloco de código do programa principal

contador = 1
while contador <= 5:
 print("Número:", contador)
 contador += 1

print('Faça sua Senha:')
senha_correta = len(input("Digite uma Senha:"))
confirm_senha = len(input("Confirme uma Senha:"))

chances = 3

if senha_correta == confirm_senha:

 while chances > 0:
    senha = len(input('Digite sua senha:'))

    if senha == confirm_senha:
      print('Sua senha está correta')
      break

    else:
      chances -= 1
      print('Seu senha está incorreta')

    if chances == 0:
      print("Sem mais Tentativas")

else:
  print('Infelizmente não poderá proseguir!')

print('Exercício 1: Contagem regressiva simples__________________________________________')
# Escreva um programa que exiba uma contagem regressiva de 10 a 1, e depois imprima "Fogo!".
cont = 10

while cont >= 1:
  print("Contagem regressiva", cont)
  cont -= 1

print('FOGO!!!!!!!!!!!!!')

print('Exercício 2: Soma de números pares________________________________________________')
# Peça ao usuário que insira um número inteiro positivo e, em seguida, calcule a soma de todos os números pares de 2 até o número inserido.
numero = int(input("Digite um número inteiro positivo: "))
soma = 0
i = 2

while i <= numero:
  soma += i
  i += 2

  print("A soma dos números pares é:", soma)

print('Exercício 3: Tabuada de multiplicação_____________________________________________')
# Peça ao usuário para inserir um número inteiro e mostre a tabuada de multiplicação desse número de 1 a 10.
num = int(input("Digite um número em 1 e 10:"))
num1 = 1

while num1 <= 10:
  print(num1, "x", num, '=', num1*num)
  num1 += 1

print('Exercício 4: Números ímpares reversos_____________________________________________')
# Exiba uma contagem regressiva de números ímpares de 99 a 1.
cont2 = 99

while cont2 >= 1:
  print("Contagem regressiva", cont2)
  cont2 -= 2